const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { setTimeout: delay } = require('node:timers/promises');
const { ReloadWatcher } = require('../out/ReloadWatcher');

test('deployment signal reloads once and activation records the new build without a reload loop', async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tg-reload-test-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const signal = path.join(dir, 'reload-signal');
  fs.writeFileSync(signal, 'previous-deployment');
  let count = 0;
  const runtime = { version: '0.4.1', buildHash: 'build-a', workspaces: ['/repo'] };
  const watcher = new ReloadWatcher(dir, runtime, async () => { count++; });
  t.after(() => watcher.dispose());
  watcher.setPort(7892);
  const registered = JSON.parse(fs.readFileSync(path.join(dir, 'sessions', `${process.pid}.json`), 'utf8'));
  assert.equal(registered.windowId, watcher.windowId);
  assert.equal(registered.port, 7892);
  assert.deepEqual(registered.workspaces, ['/repo']);
  await delay(300);
  assert.equal(count, 0);
  fs.writeFileSync(signal, 'new-deployment');
  for (let i = 0; i < 20 && count === 0; i++) await delay(50);
  assert.equal(count, 1);
  fs.writeFileSync(signal, 'new-deployment');
  await delay(350);
  assert.equal(count, 1);
  watcher.dispose();
  const restarted = new ReloadWatcher(dir, { ...runtime, buildHash: 'build-b' }, async () => { count++; });
  t.after(() => restarted.dispose());
  const receipt = JSON.parse(fs.readFileSync(path.join(dir, 'sessions', `${process.pid}.json`), 'utf8'));
  assert.equal(receipt.signal, 'new-deployment');
  assert.equal(receipt.buildHash, 'build-b');
  await delay(300);
  assert.equal(count, 1);
});
